"""
# RSA_tuner.py is a part of the RSA package.
# Copyright (C) 2024 RSA authors (see AUTHORS for details).
# RSA is licensed under the GNU GPL v3 or later, see LICENSE for details.
# Please respect the MCnet Guidelines, see GUIDELINES for details.
"""

# Implementation of the RSA_ND_tuner_Joker_locked:
# -> Joker: returns full arrays of accept, reject weights not just weights (which is accept * reject)
# -> Locked: implementation of multiple parameters locked to the same value, eg. a_d = a_u = a, where they are fitted together not separately
# -> also in this implementation we have an embedding approach for parameter value lookup in weight computation

import numpy as np
from tqdm import tqdm
import os

import torch
from torch import Tensor
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import importlib
import lund_weight_ND_Joker_locked as lund_weight_nD
import pseudo_chi2_loss
import wasserstein_loss
import wasserstein_loss_nd

importlib.reload(lund_weight_nD)
importlib.reload(pseudo_chi2_loss)
importlib.reload(wasserstein_loss)
importlib.reload(wasserstein_loss_nd)

from lund_weight_ND_Joker_locked import LundWeight
from pseudo_chi2_loss import PseudoChiSquareLoss
from wasserstein_loss import WassersteinLoss
from wasserstein_loss_nd import WassersteinLoss_nD


class RSA_nD_tuner():
    def __init__(self, epochs, dim_multiplicity, dim_accept_reject, over_sample_factor, params_base,
                 sim_observable_dataloader, sim_z_dataloader, sim_fPrel_dataloader, exp_observable_dataloader,
                 params_init = None, print_details = False, results_dir = None, fixed_binning = True, device = 'cuda', loss_type='emd', params_groups=None):
        """
        RSA-based training/tuning class for tuning microscopic dynamics (hadronization parameters) from macroscopic observables.
        
        Args:
            epochs (int): ----------------------- Number of training cycles through the full dataset
            dim_multiplicity (int): ------------- Size of the zero-padded hadronization data (largest fragmentation chain length)
            dim_accept_reject (int): ------------ Size of zero-padded accept-reject arrays (largest rejection count in events)
            over_sample_factor (float): --------- Over-sample factor used when generating the events with accept-reject
            params_base (torch tensor): --------- Parameters used when generating the simulated model data i.e. the base parameterization
            sim_observable_dataloader (string): - Path to global observable data generated by sim model
            sim_z_dataloader (string): ---------- Path to sim model kinematics generating the global observable
            exp_observable_dataloader (string): - Path to desired (experimental) global distribution (training data)
            params_init (torch tensor): --------- Initial parameters for the Lund weight module (if None, the base parameters are used)
            !NOTE! params_init define the parameters to be reweighted
            print_details (bool): --------------- Option to output intermediate results during training
            results_dir (string): --------------- Option for path to store results (if the directory doesn't exist, it will be created)
            loss_type (string): ----------------- Option for loss function type (e.g., 'emd', 'sliced_emd', 'chi2', 'Joker')
            params_groups (dict, optional): ----- Optional dictionary specifying parameter groups for reweighting (default: None) -> check if it works when params_groups=None
        """

        # Model hyperparameters
        self.epochs = epochs
        self.dim_multiplicity = dim_multiplicity
        self.dim_accept_reject = dim_accept_reject
        self.over_sample_factor = over_sample_factor
        self.params_base = params_base
        if params_init == None:
            print('No initial parameters were provided, using the base parameters instead.')
            self.params_init = self.params_base
        else:
            self.params_init = params_init
        print(self.params_init)

        # Training data
        self.exp_observable = exp_observable_dataloader
        self.sim_observable_base = sim_observable_dataloader
        self.sim_z_base = sim_z_dataloader
        self.sim_fPrel_base = sim_fPrel_dataloader
        self.print_details = print_details
        self.results_dir = results_dir
        self.fixed_binning = fixed_binning
        self.loss_type = loss_type
        self.params_groups = params_groups

        # Device
        if device == 'cuda':
            if torch.cuda.is_available():
                print('Using CUDA for training.')
                self.device = torch.device('cuda')
            else:
                print('CUDA is not available, using CPU instead.')
                self.device = torch.device('cpu')
        else:
            self.device = torch.device('cpu')

        # Initialize the Lund weight module
        torch.cuda.empty_cache()
        self.weight_nexus = LundWeight(self.params_base, self.params_init, self.params_groups, over_sample_factor = self.over_sample_factor, device= self.device)

        # Initialize the loss
        self.loss_metric_type, self.loss_component = _default_loss_settings(self.loss_type)
        self.loss_metric = _build_loss_metric(
            self.loss_metric_type,
            device = self.device,
            results_dir = self.results_dir,
            print_details = self.print_details,
            fixed_binning = self.fixed_binning,
        )
        self.loss_func = loss_func
                

        # Create a results directory if it doesn't exist
        if self.results_dir != None:
            if not os.path.exists(self.results_dir):
                os.mkdir(self.results_dir)
                print('A model directory was created at,', self.results_dir)

    def RSA_tune(self, optimizer, scheduler=None):
        #!NOTE: needs to be implemented for the 4d case
        """
        Training cycle for RSA. 

        optimizer: Specified network optimizer
        scheduler: Specified learning rate scheduler
        """

        # Choose the correct order of gradient components:
        pid_keys_map_a = {int(key.item()): i for i, key in enumerate(self.weight_nexus.a_pid_keys)}
        pid_keys_map_b = {int(key.item()): i for i, key in enumerate(self.weight_nexus.b_pid_keys)}
        sigma_ind = 0
        a_ind_lookup_pos = []
        a_ind_params_init_pos = []
        b_ind_lookup_pos = []
        b_ind_params_init_pos = []

        for p_ind, (k,_) in enumerate(self.params_init.items()):
            if k == 'sigma': 
                sigma_ind = p_ind
            elif 'a' in k:
                pid = int(k[1:])
                a_ind_lookup_pos.append(self.weight_nexus.a_pid_to_group_idx[pid_keys_map_a[pid]].item())
                # a_ind_lookup_pos.append(pid_keys_map[pid])
                a_ind_params_init_pos.append(p_ind)
            elif 'b' in k:
                pid = int(k[1:])
                b_ind_lookup_pos.append(self.weight_nexus.b_pid_to_group_idx[pid_keys_map_b[pid]].item())
                # b_ind_lookup_pos.append(pid_keys_map[pid])
                b_ind_params_init_pos.append(p_ind)     
        
        device = self.device
        # Initialize a,b array
        params_array = [[v for v in self.params_init.values()]]
        batch_counter = 0
        loss_values = []

        # Start the tuning (training) loop
        for i in tqdm(range(self.epochs), ncols = 100, disable=False):
            epoch_loss = 0
            
            batch_counter = 0
            w = next(iter(self.exp_observable))
            for (x,y,z) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base):

                z1, z2, z3 = z
                w1, w2, w3 = w
                x, y, z1, z2, z3, w1, w2, w3 = x.to(device), y.to(device), z1.to(device), z2.to(device), z3.to(device), w1.to(device), w2.to(device), w3.to(device)

                # Reset the gradients
                optimizer.zero_grad()
                # Compute the weights
                weight_outputs = self.weight_nexus(x, y)
                weights, weights_sigma, accept_weights, reject_weights = _unpack_weight_outputs(weight_outputs)

                # Compute the loss
                loss = self.loss_func(
                    [z1,z2,z3], # The 3 observables inputed into the model as observables_dataloader
                    [w1,w2,w3],
                    (weights, weights_sigma, accept_weights, reject_weights),
                    self.loss_metric, # Defines the type of metric and initializes it (eg. wasserstein distance)
                    self.loss_component,  # Dictionary with info about what kind of loss to use
                )

                loss_cpu = loss.clone().detach().cpu().numpy()
                loss_values.append(loss_cpu)
                # print('----------------------------------------------')
                # print('Loss:', loss.clone().detach().numpy())
                # Compute gradients via backprop
                # torch.autograd.set_detect_anomaly(True)
                epoch_loss += loss_cpu
                # loss.backward(create_graph=True) # For AdaHessian
                loss.backward()
                
                #!NOTE: new order optimizer.step moved before param_value saving
                # Update the network weights
                optimizer.step()
                # Update the learning rate scheduler
                if scheduler != None:
                    scheduler.step(loss)
                # Iterate the batch counter
                batch_counter+=1


                # Initialize gradient and value containers
                N = len(self.params_init)
                # print('N parameters being tuned:', N)
                param_gradient = torch.zeros(N, device='cpu')
                param_value = torch.zeros(N, device='cpu')

                for pname, param in self.weight_nexus.named_parameters():
                    # print('HEREEEE: ')
                    # print(pname, param)
                    if param.grad is None:
                        continue

                    grad = param.grad.clone().detach().cpu()
                    val = param.clone().detach().cpu()

                    if pname == "sigma_alt":
                        param_gradient[sigma_ind] = grad
                        param_value[sigma_ind] = val

                    elif "a_lookup_alt" in pname:
                        # print('1: ', a_ind_lookup_pos)
                        # print('2: ', grad.shape)
                        param_gradient[a_ind_params_init_pos] = grad[a_ind_lookup_pos].view(-1)
                        param_value[a_ind_params_init_pos] = val[a_ind_lookup_pos].view(-1)

                    elif "b_lookup_alt" in pname:
                        param_gradient[b_ind_params_init_pos] = grad[b_ind_lookup_pos].view(-1)
                        param_value[b_ind_params_init_pos] = val[b_ind_lookup_pos].view(-1)

                    else:
                        break  # avoid base (frozen) parameters
                
                # if self.print_details:
                #         # Output the gradients of parameters
                #         for ip, param in enumerate(p for p in self.weight_nexus.parameters() if p.requires_grad):
                #             print(param.grad.clone().detach().numpy())

                # # Update the network weights
                # optimizer.step()
                # # Update the learning rate scheduler
                # if scheduler != None:
                #     scheduler.step(loss)
                # # Iterate the batch counter
                # batch_counter+=1

                # Output the loss and learning rate 
                # print(f'Loss: {loss_cpu:>8f}, \n LR: {optimizer.param_groups[0]["lr"]:>8f}')
                # array_temp = [v.clone().detach().numpy()  for k,v in self.weight_nexus.params.items() if v.requires_grad == True]
                # array_temp = []
                # grad_temp = []
                # for name, param in self.weight_nexus.named_parameters():
                #     if not param.requires_grad or param.grad is None:
                #         continue

                #     grad = param.grad.clone().detach()
                #     val = param.clone().detach()
                #     # print(name, grad.shape)
                #     if val.numel() == 1:
                #         array_temp.append(val.item())
                #         grad_temp.append(grad.item())
                #     else:
                #         nonzero = val[grad != 0]
                #         array_temp.extend(nonzero.tolist())
                #         nonzero_grad = grad[grad != 0]
                #         grad_temp.extend(nonzero_grad.tolist())

                #     if len(array_temp) >= 3:
                #         break  # stop once we have 3 values
                    
                #     # print(param.grad.clone().detach().cpu().shape)
                #     # print(param.grad.clone().detach().cpu().numpy())
                #     # print(param.clone().detach().numpy())
                #     # param_gradient_i[ip] = param.grad.clone().detach()
                # array_temp = torch.tensor(array_temp, device='cpu')
                # array_temp = torch.cat([array_temp[1:], array_temp[:1]])
                # grad_temp = torch.tensor(grad_temp, device='cpu')
                # grad_temp = torch.cat([grad_temp[1:], grad_temp[:1]])
                print('----------------------------------------------')
                print(f'Loss: {loss_cpu}')
                print(f'Parameters: {param_value}')
                print(f'Gradients: {param_gradient}')
                print('----------------------------------------------')

                # Record the tuned parameters
                params_array.append(param_value.detach())
                # params_array = torch.tensor(params_array, device= 'cpu')
                
                if self.print_details and self.results_dir != None:
                    np.save(self.results_dir + '/RSA_tuning_params.npy', (params_array))
                    np.save(self.results_dir + '/RSA_tuning_loss.npy', np.array(loss_values))
                    
                torch.cuda.empty_cache()
                del x, y, z, w, weights, loss, grad, val

                
        # Return the final tuned parameters as well as the full search space path     
        # return np.array([v.clone().detach().cpu().numpy() for k,v in self.weight_nexus.params.items() if v.requires_grad == True]), np.array(params_array)
        return param_value, params_array, loss_values
    
    def RSA_flow(self, optimizer, param_grid):

        """
        Generate RSA gradient flow and loss landscape data for ND parameter space

        optimizer: Specified network optimizer
        param_grid: Initial parameter grid for the loss landscape (parameter plane grid)
        """


        # Choose the correct order of gradient components:
        pid_keys_map = {int(key.item()): i for i, key in enumerate(self.weight_nexus.pid_keys)}
        sigma_ind = 0
        a_ind_lookup_pos = []
        a_ind_params_init_pos = []
        b_ind_lookup_pos = []
        b_ind_params_init_pos = []

        for p_ind, (k,_) in enumerate(self.params_init.items()):
            if k == 'sigma': 
                sigma_ind = p_ind
            elif 'a' in k:
                pid = int(k[1:])
                a_ind_lookup_pos.append(pid_keys_map[pid])
                a_ind_params_init_pos.append(p_ind)
            elif 'b' in k:
                pid = int(k[1:])
                b_ind_lookup_pos.append(pid_keys_map[pid])
                b_ind_params_init_pos.append(p_ind)        

        device = self.device
        N = len(param_grid[0])

        # Initialize gradient tensor
        param_gradient = torch.zeros(len(param_grid), N, device=device)
        loss_grid = torch.zeros(len(param_grid), device=device)
        mu_metric = torch.zeros(len(param_grid), 2, device=device)
        N_eff_metric = torch.zeros(len(param_grid), device=device)

        init_counter = 0
        for param_point in tqdm(param_grid, ncols=100):

            param_point_dict = {
                k: v.clone().detach().to(device) for (k, _), v in zip(self.params_init.items(), param_point)
                # k: v.clone().detach().to(device).requires_grad_(True) for (k, _), v in zip(self.params_init.items(), param_point)
            } 
            #!NOTE: param_grid needs to have the same order of parameters as params_init
            if len(param_point_dict) != N:
                raise ValueError(f"Learned parameters number ({len(param_point_dict)}) does not match grid size ({N}).")

            # Create an intermediate gradient tensor
            # param_gradient_i = torch.zeros(3, device=device)
            param_gradient_i = torch.zeros(N, device=device)

            # Initialize new weight module with different initial parameters
            if self.weight_nexus != None:
                del self.weight_nexus
            torch.cuda.empty_cache()

            self.weight_nexus = LundWeight(self.params_base, param_point_dict, over_sample_factor = self.over_sample_factor, device= self.device)
            w = next(iter(self.exp_observable))
            for (x,y,z) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base):
                z1, z2, z3 = z
                w1, w2, w3 = w
                x, y, z1, z2, z3, w1, w2, w3 = x.to(device), y.to(device), z1.to(device), z2.to(device), z3.to(device), w1.to(device), w2.to(device), w3.to(device)
                # x, y, z, w = x.to(device), y.to(device), z.to(device), w.to(device)
                # Reset the gradients
                optimizer.zero_grad()
                # Compute the weights
                weight_outputs = self.weight_nexus(x, y)
                weights, weights_sigma, accept_weights, reject_weights = _unpack_weight_outputs(weight_outputs)

                # Compute the loss
                loss = self.loss_func(
                    [z1,z2,z3],
                    [w1,w2,w3],
                    (weights, weights_sigma, accept_weights, reject_weights),
                    self.loss_metric,
                    self.loss_component,
                )
                
                # Compute Performance Metrics
                mu = torch.mean(weights)
                mu_sig = torch.std(1-weights)
                N_eff = torch.sum(weights) ** 2 / torch.sum(weights ** 2) / len(weights)
                
                
                # Compute gradients via backprop
                loss.backward()

                # Print loss value
                print('----------------------------------------------')
                print('Loss:', loss.clone().detach().cpu().numpy())
                print('----------------------------------------------')
                # Save the gradients
                for pname, param in self.weight_nexus.named_parameters():
                    if param.grad is None:
                        continue
                    grad = param.grad.clone()

                    if pname == "sigma_alt":
                        param_gradient_i[sigma_ind] = grad
                    
                    elif "a_lookup_alt" in pname:
                        param_gradient_i[a_ind_params_init_pos] = grad[a_ind_lookup_pos].view(-1)
                    elif "b_lookup_alt" in pname:
                        param_gradient_i[b_ind_params_init_pos] = grad[b_ind_lookup_pos].view(-1)
                    else: 
                        break # break after b_lookup, to avoid including base parameters (without gradient)
                print('Gradient:', param_gradient_i.clone().detach().cpu().numpy())
                print('----------------------------------------------')

            param_gradient[init_counter] = param_gradient_i
            loss_grid[init_counter] = loss.clone().detach()
            mu_metric[init_counter] = torch.tensor([mu, mu_sig], device=device)
            N_eff_metric[init_counter] = N_eff.clone().detach()
            init_counter += 1

        return (
            param_gradient.detach().cpu().numpy(),
            loss_grid.detach().cpu().numpy(),
            [mu_metric.detach().cpu().numpy(), N_eff_metric.detach().cpu().numpy()],
        )



# Temporary Helpers for loss computation:

class _PseudoChiSquareMetric:
    """
    Adapter that gives PseudoChiSquareLoss the same call interface as the
    other loss metrics:
        metric(sim_values, exp_values, sim_weights)

    The division by the number of simulated entries preserves the previous
    chi2 behavior, where the raw pseudo-chi2 loss was divided by the batch size.
    """
    def __init__(self, results_dir = None, print_details = False, fixed_binning = True):
        self.loss = PseudoChiSquareLoss(
            results_dir = results_dir,
            print_details = print_details,
            fixed_binning = fixed_binning,
        )

    def __call__(self, sim_values, exp_values, sim_weights):
        return self.loss(sim_values, exp_values, sim_weights) / sim_values.shape[0]


def _build_loss_metric(loss_metric_type, device, results_dir = None, print_details = False, fixed_binning = True):
    if loss_metric_type == 'wasserstein_p1':
        return WassersteinLoss(p = 1, device = device)
    elif loss_metric_type == 'wasserstein_p2':
        return WassersteinLoss(p = 2, device = device)
    elif loss_metric_type == 'sliced_wasserstein_p1':
        return WassersteinLoss_nD(device = device, p = 1, n_projections = 128, seed = 42)
    elif loss_metric_type == 'pseudo_chi2':
        return _PseudoChiSquareMetric(
            results_dir = results_dir,
            print_details = print_details,
            fixed_binning = fixed_binning,
        )
    else:
        raise ValueError(f"Unknown loss metric type: {loss_metric_type}")


def _default_loss_settings(loss_type):
    """
    Translate the existing loss_type strings into two separate choices:
      1. the metric used to compare prepared distributions;
      2. the single loss component that prepares the distributions.
    """
    if loss_type == 'emd':
        return 'wasserstein_p1', {
            'observable': 'multiplicity',
            'weighting': 'event',
        }
    elif loss_type == 'sliced_emd':
        return 'sliced_wasserstein_p1', {
            'observable': 'multiplicity',
            'weighting': 'event',
        }
    elif loss_type == 'chi2':
        return 'pseudo_chi2', {
            'observable': 'multiplicity',
            'weighting': 'event',
        }
    elif loss_type == 'Joker':
        return 'wasserstein_p1', {
            'observable': 'z_accept',
            'mode': 'fixed_index',
            'z_index': 1,
            'weighting': 'local_accept_reject_sigma',
        }
    elif loss_type == 'Joker_nosigma':
        return 'wasserstein_p2', {
            'observable': 'z_accept',
            'mode': 'all_nonzero',
            'weighting': 'local_accept_reject',
        }
    elif loss_type == 'Joker_nosigma_chi2':
        return 'pseudo_chi2', {
            'observable': 'z_accept',
            'mode': 'all_nonzero',
            'weighting': 'local_accept_reject',
        }

    else:
        raise ValueError(f"Unknown loss type: {loss_type}")


def _unpack_weight_outputs(weight_outputs):
    """
    Standardize LundWeight outputs to:
        event_weights, sigma_weights, accept_weights, reject_weights

    For no-sigma configurations, sigma_weights is None.
    """
    if len(weight_outputs) == 3:
        event_weights, accept_weights, reject_weights = weight_outputs
        sigma_weights = None
    elif len(weight_outputs) == 4:
        event_weights, sigma_weights, accept_weights, reject_weights = weight_outputs
    else:
        raise ValueError(f"Unexpected number of weight outputs: {len(weight_outputs)}")

    return event_weights, sigma_weights, accept_weights, reject_weights


def _product_reject_weights(reject_weights_selected):
    """
    Multiply reject weights over the stored rejected trials.
    NaNs are treated as padded entries and replaced by the neutral factor 1.
    """
    reject_weights_selected = torch.where(
        torch.isnan(reject_weights_selected),
        torch.tensor(
            1.0,
            device = reject_weights_selected.device,
            dtype = reject_weights_selected.dtype,
        ),
        reject_weights_selected,
    )
    return reject_weights_selected.prod(dim = 1)


def _local_accept_reject_weights(accept_weights, reject_weights, sim_mask):
    """
    Construct local accepted-z weights:
        w_local = R_accept * product(R_reject)
    """
    accept_weights_1d = accept_weights[sim_mask].reshape(-1)
    reject_weights_1d = reject_weights[sim_mask]
    reject_weights_1d = _product_reject_weights(reject_weights_1d)

    return accept_weights_1d * reject_weights_1d


def _prepare_multiplicity_loss_inputs(sim, exp, weights, component):
    event_weights, sigma_weights, accept_weights, reject_weights = weights

    mult_sim, pT_sim, z_accept_sim = sim
    mult_exp, pT_exp, z_accept_exp = exp

    if component.get('weighting') != 'event':
        raise ValueError("Multiplicity loss currently supports only weighting='event'.")

    return mult_sim, mult_exp, event_weights


def _prepare_z_accept_loss_inputs(sim, exp, weights, component):
    event_weights, sigma_weights, accept_weights, reject_weights = weights

    mult_sim, pT_sim, z_accept_sim = sim
    mult_exp, pT_exp, z_accept_exp = exp

    mode = component.get('mode', 'all_nonzero')
    weighting = component.get('weighting', 'local_accept_reject')

    if mode == 'all_nonzero':
        sim_mask = z_accept_sim[:, :] > 0.0
        exp_mask = z_accept_exp[:, :] > 0.0

        z_accept_sim_1d = z_accept_sim[sim_mask].reshape(-1)
        z_accept_exp_1d = z_accept_exp[exp_mask].reshape(-1)
        sim_weights = _local_accept_reject_weights(accept_weights, reject_weights, sim_mask)

        if weighting == 'local_accept_reject_sigma':
            if sigma_weights is None:
                raise ValueError("weighting='local_accept_reject_sigma' requires sigma weights.")
            sim_weights = sim_weights * sigma_weights[sim_mask].reshape(-1)
        elif weighting != 'local_accept_reject':
            raise ValueError(f"Unsupported z_accept weighting: {weighting}")

        return z_accept_sim_1d, z_accept_exp_1d, sim_weights

    elif mode == 'fixed_index':
        z_index = component.get('z_index', 1)

        z_accept_sim_entry = z_accept_sim[:, z_index]
        z_accept_exp_entry = z_accept_exp[:, z_index]

        sim_mask = z_accept_sim_entry > 0
        exp_mask = z_accept_exp_entry > 0

        z_accept_sim_1d = z_accept_sim_entry[sim_mask].reshape(-1)
        z_accept_exp_1d = z_accept_exp_entry[exp_mask].reshape(-1)

        accept_weights_1d = accept_weights[:, z_index][sim_mask].reshape(-1)
        reject_weights_1d = reject_weights[:, z_index][sim_mask]
        reject_weights_1d = _product_reject_weights(reject_weights_1d)
        sim_weights = accept_weights_1d * reject_weights_1d

        if weighting == 'local_accept_reject_sigma':
            if sigma_weights is None:
                raise ValueError("weighting='local_accept_reject_sigma' requires sigma weights.")
            sim_weights = sim_weights * sigma_weights[:, z_index][sim_mask]
        elif weighting != 'local_accept_reject':
            raise ValueError(f"Unsupported z_accept weighting: {weighting}")

        return z_accept_sim_1d, z_accept_exp_1d, sim_weights

    else:
        raise ValueError(f"Unsupported z_accept mode: {mode}")


def _prepare_loss_inputs(sim, exp, weights, component):
    observable = component.get('observable')

    if observable == 'multiplicity':
        return _prepare_multiplicity_loss_inputs(sim, exp, weights, component)
    elif observable == 'z_accept':
        return _prepare_z_accept_loss_inputs(sim, exp, weights, component)
    else:
        raise ValueError(f"Unsupported loss observable: {observable}")


def loss_func(sim, exp, weights, loss_metric, loss_component):
    """
    Single loss implementation.

    The loss is computed in two steps:
      1. prepare raw sim/exp tensors and weights into a standard form;
      2. apply the selected metric to the prepared inputs.

    The metric must have the common interface:
        loss_metric(sim_values, exp_values, sim_weights)
    """
    sim_values, exp_values, sim_weights = _prepare_loss_inputs(
        sim,
        exp,
        weights,
        loss_component,
    )

    return loss_metric(
        sim_values,
        exp_values,
        sim_weights,
    )


# Backwards-compatible wrapper for direct external calls to the old name.
def loss_func_nosigma(sim, exp, weights, loss_metric):
    event_weights, accept_weights, reject_weights = weights
    weight_pack = (event_weights, None, accept_weights, reject_weights)
    loss_component = {
        'observable': 'z_accept',
        'mode': 'all_nonzero',
        'weighting': 'local_accept_reject',
    }
    return loss_func(sim, exp, weight_pack, loss_metric, loss_component)


#FUTURE IDEAS:
# imprvement:
# build it **once**
# self.weight_nexus = LundWeight(self.params_base,
#                                self.params_init,  # any placeholder
#                                over_sample_factor=self.over_sample_factor,
#                                device=self.device)

# # inside the grid loop – just overwrite tensor data
# with torch.no_grad():                    # no autograd tracking
#     for pname, new_val in zip(self.params_init.keys(), param_point):
#         self.weight_nexus.params[pname].copy_(new_val.to(self.device))

# put it after:
# for param_point in tqdm(param_grid, ncols=100):