"""
# RSA_tuner.py is a part of the RSA package.
# Copyright (C) 2024 RSA authors (see AUTHORS for details).
# RSA is licensed under the GNU GPL v3 or later, see LICENSE for details.
# Please respect the MCnet Guidelines, see GUIDELINES for details.
"""

import numpy as np
from tqdm import tqdm
import os

import torch
from torch import Tensor
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import importlib
import lund_weight_nD_temp_emb as lund_weight_nD
import pseudo_chi2_loss
import wasserstein_loss

importlib.reload(lund_weight_nD)
importlib.reload(pseudo_chi2_loss)
importlib.reload(wasserstein_loss)

from lund_weight_nD_temp_emb import LundWeight
from pseudo_chi2_loss import PseudoChiSquareLoss
from wasserstein_loss import WassersteinLoss


class RSA_nD_tuner():
    def __init__(self, epochs, dim_multiplicity, dim_accept_reject, over_sample_factor, params_base,
                 sim_observable_dataloader, sim_z_dataloader, sim_fPrel_dataloader, exp_observable_dataloader,
                 params_init = None, print_details = False, results_dir = None, fixed_binning = True, device = 'cuda'):
        """
        RSA-based training/tuning class for tuning microscopic dynamics (hadronization parameters) from macroscopic observables.
        
        Args:
            epochs (int): ----------------------- Number of training cycles through the full dataset
            dim_multiplicity (int): ------------- Size of the zero-padded hadronization data (largest fragmentation chain length)
            dim_accept_reject (int): ------------ Size of zero-padded accept-reject arrays (largest rejection count in events)
            over_sample_factor (float): --------- Over-sample factor used when generating the events with accept-reject
            params_base (torch tensor): --------- Parameters used when generating the simulated model data i.e. the base parameterization
            sim_observable_dataloader (string): - Path to global observable data generated by sim model
            sim_z_dataloader (string): ---------- Path to sim model kinematics generating the global observable
            exp_observable_dataloader (string): - Path to desired (experimental) global distribution (training data)
            params_init (torch tensor): --------- Initial parameters for the Lund weight module (if None, the base parameters are used)
            !NOTE! params_init define the parameters to be reweighted
            print_details (bool): --------------- Option to output intermediate results during training
            results_dir (string): --------------- Option for path to store results (if the directory doesn't exist, it will be created)
        """

        # Model hyperparameters
        self.epochs = epochs
        self.dim_multiplicity = dim_multiplicity
        self.dim_accept_reject = dim_accept_reject
        self.over_sample_factor = over_sample_factor
        self.params_base = params_base
        if params_init == None:
            self.params_init = self.params_base
        else:
            self.params_init = params_init

        # Training data
        self.exp_observable = exp_observable_dataloader
        self.sim_observable_base = sim_observable_dataloader
        self.sim_z_base = sim_z_dataloader
        self.sim_fPrel_base = sim_fPrel_dataloader
        self.print_details = print_details
        self.results_dir = results_dir
        self.fixed_binning = fixed_binning

        # Device
        if device == 'cuda':
            if torch.cuda.is_available():
                self.device = torch.device('cuda')
            else:
                print('CUDA is not available, using CPU instead.')
                self.device = torch.device('cpu')
        else:
            self.device = torch.device('cpu')

        # Initialize the Lund weight module
        torch.cuda.empty_cache()
        self.weight_nexus = LundWeight(self.params_base, self.params_init, over_sample_factor = self.over_sample_factor, device= self.device)

        # Initialize the loss
        # self.pseudo_chi2_loss = PseudoChiSquareLoss(results_dir = self.results_dir , print_details = self.print_details, fixed_binning = self.fixed_binning)
        self.wasserstein_loss = WassersteinLoss(p = 1, device = self.device)


        # self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        # self.device = 'cpu'

        # Create a results directory if it doesn't exist
        if self.results_dir != None:
            if not os.path.exists(self.results_dir):
                os.mkdir(self.results_dir)
                print('A model directory was created at,', self.results_dir)

    def RSA_tune(self, optimizer, scheduler=None):
        """
        Training cycle for RSA. 

        optimizer: Specified network optimizer
        scheduler: Specified learning rate scheduler
        """
        device = self.device
        # Initialize a,b array
        # params_array = [[v.clone().detach().numpy() for k,v in self.weight_nexus.params.items() if v.requires_grad == True]]
        params_array = [[v for v in self.params_init.values()]]
        batch_counter = 0
        loss_values = []

        # Start the tuning (training) loop
        for i in tqdm(range(self.epochs), ncols = 100, disable=False):
            epoch_loss = 0
            
            batch_counter = 0
            for (x,y,z,w) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base, self.exp_observable):
                # print('Batch #', batch_counter)
                x, y, z, w = x.to(device), y.to(device), z.to(device), w.to(device)
                # Reset the gradients in the optimizer
                optimizer.zero_grad()
                # Compute the weights
                weights = self.weight_nexus(x, y)
                # Compute the loss
                # loss = self.pseudo_chi2_loss(z, w, weights) / x.shape[0]
                loss = self.wasserstein_loss(z, w, weights)
                loss_cpu = loss.clone().detach().cpu().numpy()
                loss_values.append(loss_cpu)
                # print('----------------------------------------------')
                # print('Loss:', loss.clone().detach().numpy())
                # Compute gradients via backprop
                # torch.autograd.set_detect_anomaly(True)
                epoch_loss += loss_cpu
                # loss.backward(create_graph=True) # For AdaHessian
                loss.backward()
                
                # if self.print_details:
                #         # Output the gradients of parameters
                #         for ip, param in enumerate(p for p in self.weight_nexus.parameters() if p.requires_grad):
                #             print(param.grad.clone().detach().numpy())


                # Update the network weights
                optimizer.step()
                # Update the learning rate scheduler
                if scheduler != None:
                    scheduler.step(loss)
                # Iterate the batch counter
                batch_counter+=1

                # Output the loss and learning rate 
                # print(f'Loss: {loss_cpu:>8f}, \n LR: {optimizer.param_groups[0]["lr"]:>8f}')
                # array_temp = [v.clone().detach().numpy()  for k,v in self.weight_nexus.params.items() if v.requires_grad == True]
                array_temp = []
                for name, param in self.weight_nexus.named_parameters():
                    if not param.requires_grad or param.grad is None:
                        continue

                    grad = param.grad.clone().detach()
                    val = param.clone().detach()
                    # print(name, grad.shape)
                    if val.numel() == 1:
                        array_temp.append(val.item())
                    else:
                        nonzero = val[grad != 0]
                        array_temp.extend(nonzero.tolist())

                    if len(array_temp) >= 3:
                        break  # stop once we have 3 values
                    # print(param.grad.clone().detach().cpu().shape)
                    # print(param.grad.clone().detach().cpu().numpy())
                    # print(param.clone().detach().numpy())
                    # a_b_c_gradient_i[ip] = param.grad.clone().detach()
                array_temp = torch.tensor(array_temp, device='cpu')
                array_temp = torch.cat([array_temp[1:], array_temp[:1]])
                # print(f'Parameters: {array_temp}')
                # print('----------------------------------------------')

                # Record the tuned parameters
                params_array.append(array_temp.detach())
                # params_array = torch.tensor(params_array, device= 'cpu')
                
                if self.print_details and self.results_dir != None:
                    np.save(self.results_dir + '/RSA_tuning_params.npy', (params_array))
                    np.save(self.results_dir + '/RSA_tuning_loss.npy', np.array(loss_values))
                    
                torch.cuda.empty_cache()
                del x, y, z, w, weights, loss, grad, val

                
        # Return the final tuned parameters as well as the full search space path     
        # return np.array([v.clone().detach().cpu().numpy() for k,v in self.weight_nexus.params.items() if v.requires_grad == True]), np.array(params_array)
        return array_temp, params_array, loss_values
    
    def RSA_flow(self, optimizer, a_b_c_init_grid):

        """
        Generate RSA gradient flow and loss landscape data for 3D parameter space

        optimizer: Specified network optimizer
        a_b_c_init_grid: Initial parameter grid for the loss landscape (parameter plane with loss magnitudes and gradients)
        """

        device = self.device

        # Initialize gradient tensor
        a_b_c_gradient = torch.zeros(len(a_b_c_init_grid), 3, device=device)
        loss_grid = torch.zeros(len(a_b_c_init_grid), device=device)
        mu_metric = torch.zeros(len(a_b_c_init_grid), 2, device=device)
        N_eff_metric = torch.zeros(len(a_b_c_init_grid), device=device)

        init_counter = 0
        for a_b_c_init in tqdm(a_b_c_init_grid, ncols=100):

            # a_b_c_init_dict = {k: torch.tensor(v, device=device) for (k, _), v in zip(self.params_init.items(), a_b_c_init)}
            a_b_c_init_dict = {
                k: v.clone().detach().to(device) for (k, _), v in zip(self.params_init.items(), a_b_c_init)
                # k: v.clone().detach().to(device).requires_grad_(True) for (k, _), v in zip(self.params_init.items(), a_b_c_init)
            }
            # a_b_c_init_dict = self.params_init.copy()
            # for i,(k,v) in enumerate(a_b_c_init_dict.items()):
            #     a_b_c_init_dict[k] = a_b_c_init[i]  #a_b_c_init_grid needs to have the same order of parameters as params_init
            

            # Create an intermediate gradient tensor
            # a_b_c_gradient_i = torch.zeros(3, device=device)
            a_b_c_gradient_i = []

            # Initialize new weight module with different initial parameters
            if self.weight_nexus != None:
                del self.weight_nexus
            torch.cuda.empty_cache()
            self.weight_nexus = LundWeight(self.params_base, a_b_c_init_dict, over_sample_factor = self.over_sample_factor).to(device)

            for (x,y,z,w) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base, self.exp_observable):
                x, y, z, w = x.to(device), y.to(device), z.to(device), w.to(device)
                # Reset the gradients
                optimizer.zero_grad()
                # Compute the weights
                weights = self.weight_nexus(x, y)
                # Compute the loss
                # loss = self.pseudo_chi2_loss(z, w, weights) / x.shape[0]
                loss = self.wasserstein_loss(z, w, weights)
                
                
                # Compute Performance Metrics
                mu = torch.mean(weights)
                mu_sig = torch.std(1-weights)
                N_eff = torch.sum(weights) ** 2 / torch.sum(weights ** 2) / len(weights)
                
                
                # Compute gradients via backprop
                loss.backward()
                # Save the gradients of a and b
                print('----------------------------------------------')
                print('Loss:', loss.clone().detach().cpu().numpy())
                # for ip, param in enumerate(p for p in self.weight_nexus.parameters() if p.requires_grad):
                #     if param.clone().detach().cpu().numpy().shape == ():
                #         a_b_c_gradient_i[ip] = param.grad.clone().detach()
                #     else:
                #         a_b_c_gradient_i[ip] = param.grad.clone().detach()

                #     print(param.grad.clone().detach().cpu().shape)
                #     print(param.grad.clone().detach().cpu().numpy())
                #     print(param.clone().detach().numpy())
                #     # a_b_c_gradient_i[ip] = param.grad.clone().detach()
                print('----------------------------------------------')
                for name, param in self.weight_nexus.named_parameters():
                    if not param.requires_grad or param.grad is None:
                        continue

                    grad = param.grad.clone().detach()
                    # print(name, grad.shape)
                    if grad.numel() == 1:
                        a_b_c_gradient_i.append(grad.item())
                    else:
                        nonzero = grad[grad != 0]
                        a_b_c_gradient_i.extend(nonzero.tolist())

                    if len(a_b_c_gradient_i) >= 3:
                        break  # stop once we have 3 values
                    # print(param.grad.clone().detach().cpu().shape)
                    # print(param.grad.clone().detach().cpu().numpy())
                    # print(param.clone().detach().numpy())
                    # a_b_c_gradient_i[ip] = param.grad.clone().detach()
                a_b_c_gradient_i = torch.tensor(a_b_c_gradient_i, device=device)
                a_b_c_gradient_i = torch.cat([a_b_c_gradient_i[1:], a_b_c_gradient_i[:1]])
                print('Gradient:', a_b_c_gradient_i.clone().detach().cpu().numpy())
                print('----------------------------------------------')

            # Write to the master gradient tensor
            # a_b_c_gradient[init_counter] = a_b_c_gradient_i.clone()
            # # Write to the master loss tensor
            # loss_grid[init_counter] = loss.clone().detach()
            # # Metrics:
            # mu_metric[init_counter] = torch.tensor([mu.item(), mu_sig.item()])
            # N_eff_metric[init_counter] = N_eff.clone().detach()
            # # Iterate the init_counter
            # init_counter += 1

            a_b_c_gradient[init_counter] = a_b_c_gradient_i
            loss_grid[init_counter] = loss.clone().detach()
            mu_metric[init_counter] = torch.tensor([mu, mu_sig], device=device)
            N_eff_metric[init_counter] = N_eff.clone().detach()
            init_counter += 1

        # # Convert the gradient and loss tensors to numpy arrays
        # a_b_c_gradient = a_b_c_gradient.numpy()
        # loss_grid = loss_grid.numpy()

        # Return the gradients and losses
        # return a_b_c_gradient, loss_grid, [mu_metric, N_eff_metric]
        return (
            a_b_c_gradient.detach().cpu().numpy(),
            loss_grid.detach().cpu().numpy(),
            [mu_metric.detach().cpu().numpy(), N_eff_metric.detach().cpu().numpy()],
        )