"""
# RSA_tuner.py is a part of the RSA package.
# Copyright (C) 2024 RSA authors (see AUTHORS for details).
# RSA is licensed under the GNU GPL v3 or later, see LICENSE for details.
# Please respect the MCnet Guidelines, see GUIDELINES for details.
"""

import numpy as np
from tqdm import tqdm
import os

import torch
from torch import Tensor
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import importlib
import lund_weight_ND_Joker_locked as lund_weight_nD
import pseudo_chi2_loss
import wasserstein_loss
import wasserstein_loss_nd

importlib.reload(lund_weight_nD)
importlib.reload(pseudo_chi2_loss)
importlib.reload(wasserstein_loss)
importlib.reload(wasserstein_loss_nd)

from lund_weight_ND_Joker_locked import LundWeight
from pseudo_chi2_loss import PseudoChiSquareLoss
from wasserstein_loss import WassersteinLoss
from wasserstein_loss_nd import WassersteinLoss_nD


class RSA_nD_tuner():
    def __init__(self, epochs, dim_multiplicity, dim_accept_reject, over_sample_factor, params_base,
                 sim_observable_dataloader, sim_z_dataloader, sim_fPrel_dataloader, exp_observable_dataloader,
                 params_init = None, print_details = False, results_dir = None, fixed_binning = True, device = 'cuda', loss_type='emd', params_groups=None):
        """
        RSA-based training/tuning class for tuning microscopic dynamics (hadronization parameters) from macroscopic observables.
        
        Args:
            epochs (int): ----------------------- Number of training cycles through the full dataset
            dim_multiplicity (int): ------------- Size of the zero-padded hadronization data (largest fragmentation chain length)
            dim_accept_reject (int): ------------ Size of zero-padded accept-reject arrays (largest rejection count in events)
            over_sample_factor (float): --------- Over-sample factor used when generating the events with accept-reject
            params_base (torch tensor): --------- Parameters used when generating the simulated model data i.e. the base parameterization
            sim_observable_dataloader (string): - Path to global observable data generated by sim model
            sim_z_dataloader (string): ---------- Path to sim model kinematics generating the global observable
            exp_observable_dataloader (string): - Path to desired (experimental) global distribution (training data)
            params_init (torch tensor): --------- Initial parameters for the Lund weight module (if None, the base parameters are used)
            !NOTE! params_init define the parameters to be reweighted
            print_details (bool): --------------- Option to output intermediate results during training
            results_dir (string): --------------- Option for path to store results (if the directory doesn't exist, it will be created)
            loss_type (string): ----------------- Option for loss function type (e.g., 'emd', 'sliced_emd', 'chi2', 'Joker')
            params_groups (dict, optional): ----- Optional dictionary specifying parameter groups for reweighting (default: None) -> check if it works when params_groups=None
        """

        # Model hyperparameters
        self.epochs = epochs
        self.dim_multiplicity = dim_multiplicity
        self.dim_accept_reject = dim_accept_reject
        self.over_sample_factor = over_sample_factor
        self.params_base = params_base
        if params_init == None:
            print('No initial parameters were provided, using the base parameters instead.')
            self.params_init = self.params_base
        else:
            self.params_init = params_init
        print(self.params_init)

        # Training data
        self.exp_observable = exp_observable_dataloader
        self.sim_observable_base = sim_observable_dataloader
        self.sim_z_base = sim_z_dataloader
        self.sim_fPrel_base = sim_fPrel_dataloader
        self.print_details = print_details
        self.results_dir = results_dir
        self.fixed_binning = fixed_binning
        self.loss_type = loss_type
        self.params_groups = params_groups

        # Device
        if device == 'cuda':
            if torch.cuda.is_available():
                print('Using CUDA for training.')
                self.device = torch.device('cuda')
            else:
                print('CUDA is not available, using CPU instead.')
                self.device = torch.device('cpu')
        else:
            self.device = torch.device('cpu')

        # Initialize the Lund weight module
        torch.cuda.empty_cache()
        self.weight_nexus = LundWeight(self.params_base, self.params_init, self.params_groups, over_sample_factor = self.over_sample_factor, device= self.device)

        # Initialize the loss
        # self.pseudo_chi2_loss = PseudoChiSquareLoss(results_dir = self.results_dir , print_details = self.print_details, fixed_binning = self.fixed_binning)
        if self.loss_type == 'emd':
            self.loss_func = WassersteinLoss(p = 1, device = self.device)
        elif self.loss_type == 'sliced_emd':
            self.loss_func = WassersteinLoss_nD(device = self.device, p = 1, n_projections = 128, seed = 42)
        elif self.loss_type == 'chi2':
            self.loss_func = PseudoChiSquareLoss(results_dir = self.results_dir , print_details = self.print_details, fixed_binning = self.fixed_binning)
        elif self.loss_type == 'Joker':
            self.wasserstein_loss = WassersteinLoss(p = 1, device = self.device)
            self.loss_func = loss_func
        elif self.loss_type == 'Joker_nosigma':
            self.wasserstein_loss = WassersteinLoss(p = 2, device = self.device)
            self.loss_func = loss_func_nosigma
                

        # Create a results directory if it doesn't exist
        if self.results_dir != None:
            if not os.path.exists(self.results_dir):
                os.mkdir(self.results_dir)
                print('A model directory was created at,', self.results_dir)

    def RSA_tune(self, optimizer, scheduler=None):
        #!NOTE: needs to be implemented for the 4d case
        """
        Training cycle for RSA. 

        optimizer: Specified network optimizer
        scheduler: Specified learning rate scheduler
        """

        # Choose the correct order of gradient components:
        pid_keys_map_a = {int(key.item()): i for i, key in enumerate(self.weight_nexus.a_pid_keys)}
        pid_keys_map_b = {int(key.item()): i for i, key in enumerate(self.weight_nexus.b_pid_keys)}
        sigma_ind = 0
        a_ind_lookup_pos = []
        a_ind_params_init_pos = []
        b_ind_lookup_pos = []
        b_ind_params_init_pos = []

        for p_ind, (k,_) in enumerate(self.params_init.items()):
            if k == 'sigma': 
                sigma_ind = p_ind
            elif 'a' in k:
                pid = int(k[1:])
                a_ind_lookup_pos.append(self.weight_nexus.a_pid_to_group_idx[pid_keys_map_a[pid]].item())
                # a_ind_lookup_pos.append(pid_keys_map[pid])
                a_ind_params_init_pos.append(p_ind)
            elif 'b' in k:
                pid = int(k[1:])
                b_ind_lookup_pos.append(self.weight_nexus.b_pid_to_group_idx[pid_keys_map_b[pid]].item())
                # b_ind_lookup_pos.append(pid_keys_map[pid])
                b_ind_params_init_pos.append(p_ind)     
        
        device = self.device
        # Initialize a,b array
        params_array = [[v for v in self.params_init.values()]]
        batch_counter = 0
        loss_values = []

        # Start the tuning (training) loop
        for i in tqdm(range(self.epochs), ncols = 100, disable=False):
            epoch_loss = 0
            
            batch_counter = 0
            w = next(iter(self.exp_observable))
            for (x,y,z) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base):

                z1, z2, z3 = z
                w1, w2, w3 = w
                x, y, z1, z2, z3, w1, w2, w3 = x.to(device), y.to(device), z1.to(device), z2.to(device), z3.to(device), w1.to(device), w2.to(device), w3.to(device)

                # Reset the gradients
                optimizer.zero_grad()
                # Compute the weights
                if self.loss_type == 'Joker_nosigma':
                    weights, accept_weights, reject_weights = self.weight_nexus(x, y)
                else:
                    weights, weights_sigma, accept_weights, reject_weights = self.weight_nexus(x, y)
                # Compute the loss
                if self.loss_type == 'chi2':
                    loss = self.loss_func(z, w, weights) / x.shape[0]
                elif self.loss_type == 'Joker':
                    loss = self.loss_func([z1,z2,z3], [w1,w2,w3], (weights, weights_sigma, accept_weights, reject_weights), self.wasserstein_loss)
                elif self.loss_type == 'Joker_nosigma':
                    loss = self.loss_func([z1,z2,z3], [w1,w2,w3], (weights, accept_weights, reject_weights), self.wasserstein_loss)
                else:
                    loss = self.loss_func(z, w, weights)

                # # print('Batch #', batch_counter)
                # x, y, z, w = x.to(device), y.to(device), z.to(device), w.to(device)
                # # Reset the gradients in the optimizer
                # optimizer.zero_grad()

                # # Compute the weights
                # weights, weights_sigma, accept_weights, reject_weights = self.weight_nexus(x, y)

                # # Compute the loss
                # if self.loss_type == 'chi2':
                #     loss = self.loss_func(z, w, weights) / x.shape[0]
                # elif self.loss_type == 'Joker':
                #     loss = self.loss_func(z, w, (weights, weights_sigma, accept_weights, reject_weights), self.wasserstein_loss)
                # else:
                #     loss = self.loss_func(z, w, weights)

                loss_cpu = loss.clone().detach().cpu().numpy()
                loss_values.append(loss_cpu)
                # print('----------------------------------------------')
                # print('Loss:', loss.clone().detach().numpy())
                # Compute gradients via backprop
                # torch.autograd.set_detect_anomaly(True)
                epoch_loss += loss_cpu
                # loss.backward(create_graph=True) # For AdaHessian
                loss.backward()

                # Initialize gradient and value containers
                N = len(self.params_init)
                # print('N parameters being tuned:', N)
                param_gradient = torch.zeros(N, device='cpu')
                param_value = torch.zeros(N, device='cpu')

                for pname, param in self.weight_nexus.named_parameters():
                    # print('HEREEEE: ')
                    # print(pname, param)
                    if param.grad is None:
                        continue

                    grad = param.grad.clone().detach().cpu()
                    val = param.clone().detach().cpu()

                    if pname == "sigma_alt":
                        param_gradient[sigma_ind] = grad
                        param_value[sigma_ind] = val

                    elif "a_lookup_alt" in pname:
                        # print('1: ', a_ind_lookup_pos)
                        # print('2: ', grad.shape)
                        param_gradient[a_ind_params_init_pos] = grad[a_ind_lookup_pos].view(-1)
                        param_value[a_ind_params_init_pos] = val[a_ind_lookup_pos].view(-1)

                    elif "b_lookup_alt" in pname:
                        param_gradient[b_ind_params_init_pos] = grad[b_ind_lookup_pos].view(-1)
                        param_value[b_ind_params_init_pos] = val[b_ind_lookup_pos].view(-1)

                    else:
                        break  # avoid base (frozen) parameters
                
                # if self.print_details:
                #         # Output the gradients of parameters
                #         for ip, param in enumerate(p for p in self.weight_nexus.parameters() if p.requires_grad):
                #             print(param.grad.clone().detach().numpy())


                # Update the network weights
                optimizer.step()
                # Update the learning rate scheduler
                if scheduler != None:
                    scheduler.step(loss)
                # Iterate the batch counter
                batch_counter+=1

                # Output the loss and learning rate 
                # print(f'Loss: {loss_cpu:>8f}, \n LR: {optimizer.param_groups[0]["lr"]:>8f}')
                # array_temp = [v.clone().detach().numpy()  for k,v in self.weight_nexus.params.items() if v.requires_grad == True]
                # array_temp = []
                # grad_temp = []
                # for name, param in self.weight_nexus.named_parameters():
                #     if not param.requires_grad or param.grad is None:
                #         continue

                #     grad = param.grad.clone().detach()
                #     val = param.clone().detach()
                #     # print(name, grad.shape)
                #     if val.numel() == 1:
                #         array_temp.append(val.item())
                #         grad_temp.append(grad.item())
                #     else:
                #         nonzero = val[grad != 0]
                #         array_temp.extend(nonzero.tolist())
                #         nonzero_grad = grad[grad != 0]
                #         grad_temp.extend(nonzero_grad.tolist())

                #     if len(array_temp) >= 3:
                #         break  # stop once we have 3 values
                    
                #     # print(param.grad.clone().detach().cpu().shape)
                #     # print(param.grad.clone().detach().cpu().numpy())
                #     # print(param.clone().detach().numpy())
                #     # param_gradient_i[ip] = param.grad.clone().detach()
                # array_temp = torch.tensor(array_temp, device='cpu')
                # array_temp = torch.cat([array_temp[1:], array_temp[:1]])
                # grad_temp = torch.tensor(grad_temp, device='cpu')
                # grad_temp = torch.cat([grad_temp[1:], grad_temp[:1]])
                print('----------------------------------------------')
                print(f'Loss: {loss_cpu}')
                print(f'Parameters: {param_value}')
                print(f'Gradients: {param_gradient}')
                print('----------------------------------------------')

                # Record the tuned parameters
                params_array.append(param_value.detach())
                # params_array = torch.tensor(params_array, device= 'cpu')
                
                if self.print_details and self.results_dir != None:
                    np.save(self.results_dir + '/RSA_tuning_params.npy', (params_array))
                    np.save(self.results_dir + '/RSA_tuning_loss.npy', np.array(loss_values))
                    
                torch.cuda.empty_cache()
                del x, y, z, w, weights, loss, grad, val

                
        # Return the final tuned parameters as well as the full search space path     
        # return np.array([v.clone().detach().cpu().numpy() for k,v in self.weight_nexus.params.items() if v.requires_grad == True]), np.array(params_array)
        return param_value, params_array, loss_values
    
    def RSA_flow(self, optimizer, param_grid):

        """
        Generate RSA gradient flow and loss landscape data for ND parameter space

        optimizer: Specified network optimizer
        param_grid: Initial parameter grid for the loss landscape (parameter plane grid)
        """


        # Choose the correct order of gradient components:
        pid_keys_map = {int(key.item()): i for i, key in enumerate(self.weight_nexus.pid_keys)}
        sigma_ind = 0
        a_ind_lookup_pos = []
        a_ind_params_init_pos = []
        b_ind_lookup_pos = []
        b_ind_params_init_pos = []

        for p_ind, (k,_) in enumerate(self.params_init.items()):
            if k == 'sigma': 
                sigma_ind = p_ind
            elif 'a' in k:
                pid = int(k[1:])
                a_ind_lookup_pos.append(pid_keys_map[pid])
                a_ind_params_init_pos.append(p_ind)
            elif 'b' in k:
                pid = int(k[1:])
                b_ind_lookup_pos.append(pid_keys_map[pid])
                b_ind_params_init_pos.append(p_ind)        

        device = self.device
        N = len(param_grid[0])

        # Initialize gradient tensor
        param_gradient = torch.zeros(len(param_grid), N, device=device)
        loss_grid = torch.zeros(len(param_grid), device=device)
        mu_metric = torch.zeros(len(param_grid), 2, device=device)
        N_eff_metric = torch.zeros(len(param_grid), device=device)

        init_counter = 0
        for param_point in tqdm(param_grid, ncols=100):

            param_point_dict = {
                k: v.clone().detach().to(device) for (k, _), v in zip(self.params_init.items(), param_point)
                # k: v.clone().detach().to(device).requires_grad_(True) for (k, _), v in zip(self.params_init.items(), param_point)
            } 
            #!NOTE: param_grid needs to have the same order of parameters as params_init
            if len(param_point_dict) != N:
                raise ValueError(f"Learned parameters number ({len(param_point_dict)}) does not match grid size ({N}).")

            # Create an intermediate gradient tensor
            # param_gradient_i = torch.zeros(3, device=device)
            param_gradient_i = torch.zeros(N, device=device)

            # Initialize new weight module with different initial parameters
            if self.weight_nexus != None:
                del self.weight_nexus
            torch.cuda.empty_cache()

            self.weight_nexus = LundWeight(self.params_base, param_point_dict, over_sample_factor = self.over_sample_factor, device= self.device)
            w = next(iter(self.exp_observable))
            for (x,y,z) in zip(self.sim_z_base, self.sim_fPrel_base, self.sim_observable_base):
                z1, z2, z3 = z
                w1, w2, w3 = w
                x, y, z1, z2, z3, w1, w2, w3 = x.to(device), y.to(device), z1.to(device), z2.to(device), z3.to(device), w1.to(device), w2.to(device), w3.to(device)
                # x, y, z, w = x.to(device), y.to(device), z.to(device), w.to(device)
                # Reset the gradients
                optimizer.zero_grad()
                # Compute the weights
                if self.loss_type == 'Joker_nosigma':
                    weights, accept_weights, reject_weights = self.weight_nexus(x, y)
                else:
                    weights, weights_sigma, accept_weights, reject_weights = self.weight_nexus(x, y)
                # Compute the loss
                if self.loss_type == 'chi2':
                    loss = self.loss_func(z, w, weights) / x.shape[0]
                elif self.loss_type == 'Joker':
                    loss = self.loss_func([z1,z2,z3], [w1,w2,w3], (weights, weights_sigma, accept_weights, reject_weights), self.wasserstein_loss)
                elif self.loss_type == 'Joker_nosigma':
                    loss = self.loss_func([z1,z2,z3], [w1,w2,w3], (weights, accept_weights, reject_weights), self.wasserstein_loss)
                else:
                    loss = self.loss_func(z, w, weights)
                
                # Compute Performance Metrics
                mu = torch.mean(weights)
                mu_sig = torch.std(1-weights)
                N_eff = torch.sum(weights) ** 2 / torch.sum(weights ** 2) / len(weights)
                
                
                # Compute gradients via backprop
                loss.backward()

                # Print loss value
                print('----------------------------------------------')
                print('Loss:', loss.clone().detach().cpu().numpy())
                print('----------------------------------------------')
                # Save the gradients
                for pname, param in self.weight_nexus.named_parameters():
                    if param.grad is None:
                        continue
                    grad = param.grad.clone()

                    if pname == "sigma_alt":
                        param_gradient_i[sigma_ind] = grad
                    
                    elif "a_lookup_alt" in pname:
                        param_gradient_i[a_ind_params_init_pos] = grad[a_ind_lookup_pos].view(-1)
                    elif "b_lookup_alt" in pname:
                        param_gradient_i[b_ind_params_init_pos] = grad[b_ind_lookup_pos].view(-1)
                    else: 
                        break # break after b_lookup, to avoid including base parameters (without gradient)
                print('Gradient:', param_gradient_i.clone().detach().cpu().numpy())
                print('----------------------------------------------')

            param_gradient[init_counter] = param_gradient_i
            loss_grid[init_counter] = loss.clone().detach()
            mu_metric[init_counter] = torch.tensor([mu, mu_sig], device=device)
            N_eff_metric[init_counter] = N_eff.clone().detach()
            init_counter += 1

        return (
            param_gradient.detach().cpu().numpy(),
            loss_grid.detach().cpu().numpy(),
            [mu_metric.detach().cpu().numpy(), N_eff_metric.detach().cpu().numpy()],
        )

def loss_func(sim, exp, weights, wasserstein_loss):
    # calculates sliced wasserstein for Joker observables
    
    weights, sigma_weights, accept_weights, reject_weights = weights
    mult_sim, pT_sim, z_accept_sim = sim
    mult_exp, pT_exp, z_accept_exp = exp
    loss = 0.0

    mult_loss = wasserstein_loss(mult_sim, mult_exp, weights)

    # sigma_weights_1d = sigma_weights.reshape(-1)
    # pT_exp_1d = pT_exp.reshape(-1)
    # pT_sim_1d = pT_sim.reshape(-1)
    
    # mask_sim = (pT_sim_1d!=0)
    # mask_exp = (pT_exp_1d!=0)

    # pT_exp_1d = pT_exp_1d[mask_exp]
    # pT_sim_1d = pT_sim_1d[mask_sim]
    # sigma_weights_1d = sigma_weights_1d[mask_sim]
    # sigma_weights_1d.reshape(-1)

    # pT_loss = wasserstein_loss(pT_sim_1d, pT_exp_1d, sigma_weights_1d)  

    # z_accept_sim_1d = z_accept_sim[z_accept_sim[:,:] > 0].reshape(-1)
    # z_accept_exp_1d = z_accept_exp[z_accept_exp[:,:] > 0].reshape(-1)
    # accept_weights_1d = accept_weights[z_accept_sim[:,:] > 0.0].reshape(-1)
    # reject_weights_1d = reject_weights[z_accept_sim[:,:] > 0.0]
    # reject_weights_1d = torch.where(
    # torch.isnan(reject_weights_1d),
    #     torch.tensor(1., device=reject_weights_1d.device),
    #     reject_weights_1d
    # ).prod(dim=1)
    # sigma_weights_1d = sigma_weights[z_accept_sim[:,:] > 0.0]
    # weights_1d = accept_weights_1d * reject_weights_1d * sigma_weights_1d
    # z_loss = wasserstein_loss(z_accept_sim_1d, z_accept_exp_1d, weights_1d)
    
    #only first line
    # print('SHAPES: ')
    # print(z_accept_sim.shape)
    # print(z_accept_exp.shape)
    # print(accept_weights.shape)
    # print(reject_weights.shape)
    # print(sigma_weights.shape)
    # print('----------------------------------------------')
    z_accept_sim_1d = z_accept_sim[:,1][z_accept_sim[:,1] > 0].reshape(-1)
    z_accept_exp_1d = z_accept_exp[:,1][z_accept_exp[:,1] > 0].reshape(-1)
    accept_weights_1d = accept_weights[:,1][z_accept_sim[:,1] > 0.0].reshape(-1)
    reject_weights_1d = reject_weights[:,1][z_accept_sim[:,1] > 0.0]
    reject_weights_1d = torch.where(
    torch.isnan(reject_weights_1d),
        torch.tensor(1., device=reject_weights_1d.device),
        reject_weights_1d
    ).prod(dim=1)
    sigma_weights_1d = sigma_weights[:,1][z_accept_sim[:,1] > 0.0]
    weights_1d = accept_weights_1d * reject_weights_1d * sigma_weights_1d
    z_loss = wasserstein_loss(z_accept_sim_1d, z_accept_exp_1d, weights_1d)
    
    # loss = mult_loss + pT_loss + z_loss
    loss = z_loss
    return loss

def loss_func_nosigma(sim, exp, weights, wasserstein_loss):
    # calculates sliced wasserstein for Joker observables
    
    weights, accept_weights, reject_weights = weights
    mult_sim, pT_sim, z_accept_sim = sim
    mult_exp, pT_exp, z_accept_exp = exp
    loss = 0.0

    mult_loss = wasserstein_loss(mult_sim, mult_exp, weights) 

    # z_accept_sim_1d = z_accept_sim[z_accept_sim[:,:] > 0].reshape(-1)
    # z_accept_exp_1d = z_accept_exp[z_accept_exp[:,:] > 0].reshape(-1)
    # accept_weights_1d = accept_weights[z_accept_sim[:,:] > 0.0].reshape(-1)
    # reject_weights_1d = reject_weights[z_accept_sim[:,:] > 0.0]
    # reject_weights_1d = torch.where(
    # torch.isnan(reject_weights_1d),
    #     torch.tensor(1., device=reject_weights_1d.device),
    #     reject_weights_1d
    # ).prod(dim=1)
    # weights_1d = accept_weights_1d * reject_weights_1d
    # z_loss = wasserstein_loss(z_accept_sim_1d, z_accept_exp_1d, weights_1d)
    
    # #only first line
    # print('SHAPES: ')
    # print(z_accept_sim.shape)
    # print(z_accept_exp.shape)
    # print(accept_weights.shape)
    # print(reject_weights.shape)
    # print('----------------------------------------------')
    z_accept_sim_1d = z_accept_sim[:,1][z_accept_sim[:,1] > 0].reshape(-1)
    z_accept_exp_1d = z_accept_exp[:,1][z_accept_exp[:,1] > 0].reshape(-1)
    accept_weights_1d = accept_weights[:,1][z_accept_sim[:,1] > 0.0].reshape(-1)
    reject_weights_1d = reject_weights[:,1][z_accept_sim[:,1] > 0.0]
    reject_weights_1d = torch.where(
    torch.isnan(reject_weights_1d),
        torch.tensor(1., device=reject_weights_1d.device),
        reject_weights_1d
    ).prod(dim=1)
    weights_1d = accept_weights_1d * reject_weights_1d 
    z_loss = wasserstein_loss(z_accept_sim_1d, z_accept_exp_1d, weights_1d)
    
    loss = z_loss
    # loss = z_loss
    return loss




# def loss_func(sim, exp, weights, wasserstein_loss):
#     """
#     Memory-lean version of the original loss.
#     Preserves exact functionality/results.
#     """
#     # Unpack
#     mult_sim, pT_sim, z_accept_sim = sim
#     mult_exp, pT_exp, z_accept_exp = exp
#     weights, sigma_weights, accept_weights, reject_weights = weights  # keep order

#     # --- 1) Multiplicity loss (as-is) ---
#     mult_loss = wasserstein_loss(mult_sim, mult_exp, weights)

#     # --- 2) pT loss (flatten by view, mask once) ---
#     # Use .ravel() (view) to avoid allocations; boolean mask+select yields 1D as needed
#     pT_sim_1d = pT_sim.ravel()
#     pT_exp_1d = pT_exp.ravel()
#     sigw_1d   = sigma_weights.ravel()

#     mask_sim = pT_sim_1d.ne(0)       # (sim mask)
#     mask_exp = pT_exp_1d.ne(0)       # (exp mask)

#     pT_sim_sel = pT_sim_1d.masked_select(mask_sim)
#     pT_exp_sel = pT_exp_1d.masked_select(mask_exp)
#     sigw_sel   = sigw_1d.masked_select(mask_sim)

#     pT_loss = wasserstein_loss(pT_sim_sel, pT_exp_sel, sigw_sel)

#     # --- 3) z-accept loss ---
#     # Build a 2D mask once (same as (z_accept_sim[:,:] > 0.0))
#     mask_z = z_accept_sim.gt(0.0)  # shape (B, T), True where "accept" exists

#     # Indices for once-only gather on the first two dims
#     idx = mask_z.nonzero(as_tuple=True)  # (rows, cols)

#     # Select z arrays
#     z_accept_sim_sel = z_accept_sim[idx]
#     z_accept_exp_sel = z_accept_exp[idx]

#     # Accept weights selection
#     accept_w_sel = accept_weights[idx]

#     # Sigma weights aligned with the same (B,T) mask
#     sigma_w_sel = sigma_weights[idx]

#     # Reject weights:
#     #   - Make NaNs -> 1 *once* to avoid creating multiple temp tensors
#     #   - Then select corresponding (B,T, R) slices and reduce product over last dim
#     #     NOTE: The original code did: select -> nan->1 -> prod(dim=1).
#     #     Doing nan->1 first is mathematically identical and more memory-friendly.
#     reject_weights_clean = torch.nan_to_num(reject_weights, nan=1.0)
#     # Select with the same (B,T) mask on the first two dims; keep all rejects on last dim
#     # idx expands naturally across the first two dims
#     reject_w_sel = reject_weights_clean[idx]  # shape: (N_selected, R)
#     reject_w_prod = reject_w_sel.prod(dim=-1)  # (N_selected,)

#     # Combine weights per selected accept
#     weights_1d = accept_w_sel * reject_w_prod * sigma_w_sel

#     # Final z-loss
#     z_loss = wasserstein_loss(z_accept_sim_sel, z_accept_exp_sel, weights_1d)

#     # --- Total ---
#     return mult_loss + pT_loss + z_loss





#FUTURE IDEAS:
# imprvement:
# build it **once**
# self.weight_nexus = LundWeight(self.params_base,
#                                self.params_init,  # any placeholder
#                                over_sample_factor=self.over_sample_factor,
#                                device=self.device)

# # inside the grid loop – just overwrite tensor data
# with torch.no_grad():                    # no autograd tracking
#     for pname, new_val in zip(self.params_init.keys(), param_point):
#         self.weight_nexus.params[pname].copy_(new_val.to(self.device))

# put it after:
# for param_point in tqdm(param_grid, ncols=100):